name: "🐛 Bug Report"
description: Tell me what I broke again
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!** Please make sure you've already searched for similar issue before creating a new one.

  - type: textarea
    id: bug-explanation
    attributes:
      label: What is the issue?
      description: A clear and concise description of what the bug is.
      placeholder: |
        Typo, crash, wrong behavior...
    validations:
      required: true

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      description: Describe how this bug occurred so I can try to reproduce it.
      placeholder: |
        I was doing this when that occurred...
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: Paste any relevant logs, error output, etc.
      description: |
        Please copy and paste any relevant log output, which will be automatically formatted into code (no need for backticks).
        If it’s long, please paste to https://pastebin.com/ (or any paste service) and copy the link here.
      render: shell

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Your device(s)

  - type: dropdown
    id: device-os
    attributes:
      label: What OS are you seeing the problem on?
      options:
        - iOS
        - iPadOS
      multiple: true
    validations:
      required: true

  - type: input
    id: device-os-version
    attributes:
      label: What is the OS version?
      description: |
        If you checked both iOS and iPadOS, please specify the 2 versions
      placeholder: "e.g. 14.5.1"
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: Which device model is it?
      placeholder: "e.g. iPhone X"
    validations:
      required: true

  - type: input
    id: device-jailbreak
    attributes:
      label: Which jailbreak is it using?
      placeholder: "e.g. checkra1n"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"
  
  - type: checkboxes
    id: duplicates-agreement
    attributes:
      label: Duplicates
      options:
        - label: I have checked that my problem has not already been mentioned recently in an existing issue
          required: true